### ISSUE TITLE
Make FastBoot testing accesible to the masses

### ISSUE THREAD

**Issue by cibernox** [ember-fastboot/ember-cli-fastboot#111] opened 2016-02-04 00:14 UTC
A discussed in the meeting, the testing story for FastBoot has to improve. There is no literature about it and is conceptually so different to the rest of the testing in the ember ecosystem that previous knowledge barely apply.

This is a living list that will probably grow.

Some points on the air to be fixed in the core packages.
- [x] Should FastBoot tests be in `/tests/fastboot` or in `/fastboot-tests`? *_/fastboot-tests *_
- [x] Find a way of running the server and the tests in the same process, using fastboot as a middleware.
- [ ] Integrate it with testem and QUnit for consistency.
- [x] Devs need/want to assert over DOM, not over strings (~~and using jQuery~~**No jquery**). A `moduleForFastboot` helper that uses jsdom inside can make this easier.
- [ ] Generators: This addon should hook into generator for routes to generate a fastboot test for that route too.
- [ ] ~~Testing for apps and testing for addons are very different. Addons might need a completely different approach with time, with on-the-flight apps.~~ **This is a long term shot.**
- [ ] Write a comprehensive guide once previous points are sorted.

Tasks outside that core that will also prevent good testing experience:
- [ ] Ember-cli-mirage doesn't work in FastBoot, probably because of pretender.js not working in node. How will this integrate with ember-network?
- [ ] Popular Authentication addons (torii, ember-simple-auth) will need to provide helpers to ease session management.
- [ ] Eventually, the "Has meaningful FastBoot tests" might become another criteria for addons in EmberObserver.

**Comment by tomdale** [comment] 2016-06-24 17:49
@cibernox Any update on this?

**Comment by simonihmig** [comment] 2016-09-24 21:07
Just released [ember-fastboot-addon-tests](https://github.com/kaliber5/ember-fastboot-addon-tests), which tries to make Fastboot testing easy. This is targeting the addon testing story only, not apps. Feedback is certainly welcome! :)

**Comment by mfazekas** [comment] 2016-12-31 16:11
FYI there is a demo of using mirage through express.js in fastboot mode. https://github.com/mfazekas/fastboot-mirage-test and https://github.com/samselikoff/ember-cli-mirage/pull/975

**Comment by tchak** [comment] 2017-01-03 18:58
It seems most work is focusing on integration tests. I am mostly interested in unit tests (especially in addons). It seems that we should be able to run them as is in fastboot just with a different reporter for QUnit. Anyone had any luck with that? Any reasons why this would not work?

**Comment by bcardarella** [comment] 2017-01-12 13:46
For us the acceptance tests rendering without error would yield the highest value. I'm also seeing stack traces during the render cycle for fastboot that don't cause the app to crash. I suspect these false positives are impacting render time. If this a failsafe that is by design in fastboot? If not it would be really nice if these would cause test failures in the eventual fastboot testing story.

**Comment by simonihmig** [comment] 2017-02-10 12:31
Being kind of a stripped down version of `ember-fastboot-addon-tests`, you can use this to write e2e FastBoot tests for you apps: https://github.com/kaliber5/ember-fastboot-app-tests

**Comment by kratiahuja** [comment] 2017-05-26 20:41
Given there is a way for addons and apps to write acceptance test that quite a few addons are using, we can close this. @tchak If you would like to have unit test, could you expose an API in `ember-cli-addon-tests` or `ember-fastboot-app-tests`.

**Closed by kratiahuja** 2017-05-26 20:41 UTC
