### ISSUE TITLE
Implement a fix for the `<title>` tag when rehydration is enabled

### ISSUE THREAD

**Issue by mansona** [ember-fastboot/ember-cli-fastboot#659] opened 2019-02-15 20:03 UTC
I only have a shallow understanding of this issue so anyone who can do it more justice please feel free to edit this description 👍 

As was reported in https://github.com/glimmerjs/glimmer-vm/issues/796 there have been some issues where Fastboot has been adding comment nodes to track rehydration to the `<title>` tag but because the browser does not "interpret" any html contained in the `<title>` tag, the full text of the comments will be output in the browser's title. This will then immediately flash when Ember boots and the comments are removed.

As this is quite a high impact issue and it is likely to affect quite a few people who intend to use Fastboot in production we need to come up with a solution that is workable for everyone.

Current proposed potential solutions:

- Special-case the title tag and make Fastboot more smart about the rendering and rehydration of this one tag.
- Implement a linting system that warned about cases that would cause issues with the title tag
- Implement some sort of AST in the Fastboot engine that would be able to rewrite any problematic tags (like `<title>`) in a more effective way.

One thing to consider when implementing a solution to this issue: we need to not just make sure that the HTML that is "returned from the server" is correct, we also need to make sure that the rehydration code also knows how to deal with the special case when trying to update the DOM. For example, if we took a purely naive approach to this we might end up with **duplicate** `<title>` tags, which would not give the desired behaviour because the second `<title>` tag would not "win" over the first 👍

**Comment by rondale-sc** [comment] 2019-02-15 21:25
I think I'm more in favor of special-casing the title tag since it is the most common problem facing consumers of rehydro-fastboot, fwiw, Thanks for writing up the issue @mansona!

**Comment by rwjblue** [comment] 2019-02-15 22:46
To clarify/flesh out my AST transform proposal, I was thinking of something that would rewrite:

```hbs
<title>Foo{{blah}}</title>
```

To:

```hbs
{{-fastboot-set-title (concat "Foo" blah)}}
```

Where the implementation of `-fastboot-set-title` would be _something_ like:

```js
export default helper(function([title]) {
  if (typeof FastBoot === 'undefined') {
    document.title = title;
    return '';
  } else {
    return htmlSafe(`<title>${title}</title>`);
  }
});
```

This is _completely_ feasible to do inside ember-cli-fastboot today and would work on all supported Ember versions (basically 2.18+).

**Comment by CvX** [comment] 2019-02-15 23:04
What about `<script>` tags, for cases like this:

```js
```

**Comment by kiwiupover** [comment] 2019-02-15 23:15
@CvX it seems that a helper to the one @rwjblue has above would work for this case. 

Everyone using rehydration will hit the <title> issue where as less developers will hit the `<script>`,  `<code>`  and `<pre>` issues. 

I think an addon could address the other cases.

**Comment by josemarluedke** [comment] 2019-03-06 00:54
I can confirm that the approach defined by @rwjblue works fine. I have defined the following helper in my application (full content for future reference..) using TS.

```ts

/*eslint no-undef: ["error", { "typeof": true }] */
declare const FastBoot: never;

import { helper } from '@ember/component/helper';
import { htmlSafe } from '@ember/string';
import { SafeString } from 'handlebars';

// This is required for FastBoot Rehydration
// See more here:
// https://github.com/ember-fastboot/ember-cli-fastboot/issues/659
export function fastbootSetTitle(
  [title]: [string] /*, hash*/
): string | SafeString {
  if (typeof FastBoot === 'undefined') {
    document.title = title;
    return '';
  } else {
    return htmlSafe(`<title>${title}</title>`);
  }
}

export default helper(fastbootSetTitle);

```

**Comment by rwjblue** [comment] 2019-03-06 01:41
@josemarluedke - Would you mind opening a PR adding that here? I'm happy to walk you through the AST transform bit if you have the time/energy to push this forward...

**Comment by lougreenwood** [comment] 2019-05-30 17:09
Just stumbled across this issue. Does anything need doing to get this into a release? I'm currently over committed on my open source work but can maybe help in a couple of weeks...?

**Comment by dnalagatla** [comment] 2019-06-28 06:10
> I think I'm more in favor of special-casing the title tag since it is the most common problem facing consumers of rehydro-fastboot, fwiw, Thanks for writing up the issue @mansona!

I agree @rondale-sc. the issue is not limited to the title though. We would need to special case the tags such as `title`, `style` and `script` as including markers in those can have a negative impact.

**Comment by rwjblue** [comment] 2019-06-28 14:15
FWIW, I believe that @kiwiupover has a spike of the approach I described above.

**Comment by CvX** [comment] 2019-06-28 14:24
Btw. I also worked on an alternative, low-level solution (in `simple-html-tokenizer` and `glimmer-vm`). It supports `<title>`, `<style>`, and `<script>`.

I gotta fix remaining minor issues, but seems to be working overall! I’ll share the results shortly. 🙂

**Comment by rwjblue** [comment] 2019-06-28 16:23
@CvX - Awesome!

**Comment by kiwiupover** [comment] 2019-06-28 16:42
Here is an AST transform for the `title`

https://astexplorer.net/#/gist/f8581d617f2edb89057682bdf38091d2/e11cdfe7ae8f33231994847776e9532ea5a94b10

**Comment by CvX** [comment] 2019-06-28 17:41
Cross-posting for those not following the glimmer-vm issue: 😉 https://github.com/glimmerjs/glimmer-vm/issues/796#issuecomment-506818798

**Closed** 2019-08-13 16:47 UTC
