### ISSUE TITLE
`ember fastboot` doesn't rebuild assets that are served with `--serve-assets`

### ISSUE THREAD

**Issue by hhff** [ember-fastboot/ember-cli-fastboot#151] opened 2016-03-30 19:25 UTC
I think the `ember fastboot` build process should also rebuild static assets in the build step by default.

Currently, if I make changes to my app, then run `ember fastboot --serve-assets`, the changes I've made aren't reflected in the application after it is "redrawn".  I have to manually rebuild before fastbooting.

Is this by design?  This would def slow down the booting process, but given `fastboot` is designed to be long running, I think rebuilding the underlying app assets on fastboot is a sensible default, and probably something users could opt out of with a flag `--no-rebuild` or something.

**Comment by leo** [comment] 2016-05-29 14:14
https://github.com/ember-fastboot/ember-cli-fastboot/pull/200

**Comment by leo** [comment] 2016-05-29 14:16
@hhff In my opinion, this issue can now be closed (since the PR I've mentioned introduces this feature).

**Comment by danmcclain** [comment] 2016-05-31 22:33
We can leave this open until #200 lands, @leo 

@hhff This was by design originally (sort of), as `ember fastboot` had no way to reload assets (specifically for the server). Once `fastboot` could reload assets/config this became possible

**Comment by danmcclain** [comment] 2016-06-24 17:41
#200 landed 🚢

**Closed** 2016-06-24 17:40 UTC
