### ISSUE TITLE
Wrong route loaded in fastboot

### ISSUE THREAD

**Issue by Gaurav0** [ember-fastboot/ember-cli-fastboot#208] opened 2016-06-03 19:29 UTC
Given this router.js:

```
Router.map(function() {
  this.route('gist', {path: '/'}, function() {
    this.route('new', {path: '/'});
  });
  this.route('twiddles');
});
```

when going to `localhost:3000/twiddles`, the `gist.new` route is loaded in fastboot instead of the `twiddles` route which is loaded normally.

Result in Ember Twiddle

![wrong route](https://cloud.githubusercontent.com/assets/313960/15790733/f3722b8a-29a0-11e6-858c-d7d20b53f27e.gif)

**Comment by jasonmit** [comment] 2016-06-03 19:30
What version of Ember?

**Comment by Gaurav0** [comment] 2016-06-03 19:36
I'm running ember-cli 2.6 beta 3 with Ember 2.5.1

**Comment by tomdale** [comment] 2016-06-24 17:30
This seems bad. I can't think of any obvious reasons this would happen off the top of my head, since the route parsing logic doesn't depend on browser behavior. Maybe a bug in `NoneLocation`?

**Comment by jasonmit** [comment] 2017-01-06 00:07
I'm running into what feels like a variant of this bug.

```js
Router.map(function() {
  this.route('welcome', { path: '/' );
  this.route('products', {path: '/products'}, function() {
    this.route('product', {path: '/:name'});
  });
});
```

Requests via Fastboot to `/products/foo` serve up the welcome route `/`

**Comment by kratiahuja** [comment] 2017-05-21 21:23
@Gaurav0 is this still an issue?

**Comment by Gaurav0** [comment] 2017-05-21 21:45
Yes, can still reproduce.

**Comment by stefanpenner** [comment] 2017-05-21 21:59
@Gaurav0 on master or..

**Comment by Gaurav0** [comment] 2017-05-22 00:38
Had tried on beta.18. I'll give rc.1 a try...

**Comment by stefanpenner** [comment] 2017-05-22 01:20
Hmm. It's unlikely there will be a difference.   But worth a go....

My guess is that this may be an ember bug. If you could provide a repo with the minimal reproduction I will gladly debug this week.

**Comment by kratiahuja** [comment] 2017-05-22 01:22
Yeah I think if you can turn on debugg logging and see what is the incoming path `fastboot` gets that will help us nail down the issue. If the incomign `path` is wrong to the `visit` API, it would mean it's somewhere in the fastboot land.

**Comment by Gaurav0** [comment] 2017-05-23 20:29
@kratiahuja It is getting the correct incoming path according to debugging. I guess the bug must be in Ember itself then?

I tried making a minimal reproduction, but it works correctly.

**Comment by kratiahuja** [comment] 2017-05-23 20:32
Yup it is an ember bug then.

**Comment by kratiahuja** [comment] 2017-05-23 22:58
Closing this since it isn't a fastboot issue.

**Closed by kratiahuja** 2017-05-23 22:58 UTC
Labels: Bug
